### ISSUE TITLE
What's this

### ISSUE THREAD

**Issue by elifoster** [trajing/YACM#1]
You should probably write a README file

**Comment by RX14** [comment]
It's a computer mod using ruby.

**Comment by elifoster** [comment]
Ah. There's not enough code for me to have figured that out. I figured it was "Yet Another Core Mod", and that some other mod that @trajing develops required a block of ruby. Still, a README or at least a desc would be handy.

**Comment by RX14** [comment]
Well, as you can see this is super duper early code...
